CREATE DATABASE IF NOT EXISTS `numelops_asso_v2`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT USAGE ON *.* TO 'v2num_user'@'localhost' IDENTIFIED BY 'WUNAzP5hw2si2EnQjavy'
  WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT USAGE ON *.* TO "v2num_user"@"%" IDENTIFIED BY "WUNAzP5hw2si2EnQjavy"
  WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `numelops_asso_v2`.* TO 'v2num_user'@'%';
GRANT ALL PRIVILEGES ON `numelops_asso_v2`.* TO 'v2num_user'@'localhost';
