CREATE DATABASE IF NOT EXISTS `numelops_asso_trans`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT USAGE ON *.* TO 'num_user'@'localhost' IDENTIFIED BY 'HtVj4f3pGtw2BC8mzgDwxj'
  WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT USAGE ON *.* TO "num_user"@"%" IDENTIFIED BY "HtVj4f3pGtw2BC8mzgDwxj"
  WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `numelops_asso_trans`.* TO 'num_user'@'%';
GRANT ALL PRIVILEGES ON `numelops_asso_trans`.* TO 'num_user'@'localhost';
